/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BudgetManager: typeof import('./src/components/settings/BudgetManager.vue')['default']
    CalendarView: typeof import('./src/components/CalendarView.vue')['default']
    CategoryManager: typeof import('./src/components/settings/CategoryManager.vue')['default']
    DynamicIcon: typeof import('./src/components/DynamicIcon.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    Hover3D: typeof import('./src/components/Hover3D.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/Toast.vue')['default']
    TransactionDialog: typeof import('./src/components/TransactionDialog.vue')['default']
  }
}
